### ISSUE TITLE
How to extend?

### ISSUE THREAD

**Issue by aivchen** [flopp/go-staticmaps#49]
I want to have an ability to add custom markers. For example I would like to override draw method. What is the best way to do it?

**Comment by flopp** [comment]
Hm. Currently, it's not easy to add another `MapObject`(e.g. a custom marker object), since you would also need change `Context` (especially the `Render` and `RenderWithTransformer` functions).
I'm actually planning to add marker objects with custom images (=> issue #48), would these be sufficient for your use case?

**Comment by aivchen** [comment]
I think it would be good to have an ability to develop your own objects implementing MapObject interface. I've already added this feature in my fork (I'm not a golang developer so I'm not sure I did it in a right way): https://github.com/Airportia/go-staticmaps/commit/f3885f8d6f9fa37af07dd2f20599e2b8d707bf1e

My changes break backward compatibility but you can do something similar in new major version.

**Comment by flopp** [comment]
You're right. Adding custom MapObjects should definitely be possible. I'll look into your changed and see what I can do.

**Comment by flopp** [comment]
I've extended `Context` with a "generic" `AddObject` method, that lets the user add custom objects implementing the `MapObject` interface. I've also added an example doing exactly that: https://github.com/flopp/go-staticmaps/blob/master/examples/stars.go

**Comment by aivchen** [comment]
Great. Thank you a lot! You are awesome!
